name: Flask CI/CD Pipeline

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]
  release:
    types: [created]

jobs:

# -------------------------
# 1. BUILD & TEST
# -------------------------
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: pytest -v

# -------------------------
# 2. DEPLOY TO STAGING
# -------------------------
  deploy-staging:
    needs: build-test
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
       - name: Deploy to Staging
         run: |
          echo "Deploying to STAGING..."
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} "
          cd flask-app &&
          git pull origin staging &&
          docker compose down &&
          docker compose up -d --build
          "
      # - name: Deploy to Staging via SSH
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.STAGING_HOST }}
      #     username: ${{ secrets.STAGING_USER }}
      #     key: ${{ secrets.STAGING_SSH_KEY }}
      #     port: 22
      #     script: |
      #       echo "🚀 Deploying to STAGING..."

      #       cd ~/flask-app || exit 1

      #       echo "📥 Pull latest code"
      #       git pull origin staging

      #       echo "🛑 Stop old containers"
      #       docker compose down

      #       echo "🔨 Build new containers"
      #       docker compose up -d --build

      #       echo "🧹 Cleanup"
      #       docker image prune -f

# -------------------------
# 3. DEPLOY TO PRODUCTION
# -------------------------
  deploy-production:
    needs: build-test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: 22
          script: |
            echo "🚀 Deploying to PRODUCTION..."

            cd ~/flask-app || exit 1

            echo "📥 Pull latest code"
            git pull origin main

            echo "🛑 Stop old containers"
            docker compose down

            echo "🔨 Build new containers"
            docker compose up -d --build

            echo "🧹 Cleanup"
            docker image prune -f